<?php

namespace AppBundle\Repository;

/**
 * DetallePedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetallePedidoRepository extends \Doctrine\ORM\EntityRepository
{
    public function cantidadPorDia($idProducto, $fechaInicio,$fechaFin) {

        $q = $this->getEntityManager()->createQueryBuilder()
                ->select('p.fechaCierre, SUM(d.cantidadRecibida) as cantidad')
                ->from('AppBundle:DetallePedido', 'd')
                ->join('AppBundle:Pedido', 'p', 'WITH', 'd.pedido=p.id')
                ->where('p.fechaCierre >= :inicio')
                ->andWhere('p.fechaCierre <= :fin')
                ->andWhere('d.producto = :producto')
                ->groupBy('p.fechaCierre')
                ->setParameter("inicio", $fechaInicio)
                ->setParameter("fin", $fechaFin)
                ->setParameter("producto", $idProducto)
                ;
        return $q->getQuery()->getResult();
    }

}
