<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Producto;
/**
 * DetalleEnvioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleEnvioRepository extends \Doctrine\ORM\EntityRepository {

    public function cantidadPorDia($idProducto, $fechaInicio, $fechaFin) {

        $q = $this->getEntityManager()->createQueryBuilder()
                ->select('p.fecha, SUM(d.cantidad) as cantidad')
                ->from('AppBundle:DetalleEnvio', 'd')
                ->join('AppBundle:Envio', 'p', 'WITH', 'd.envio=p.id')
                ->where('p.fecha >= :inicio')
                ->andWhere('p.fecha <= :fin')
                ->andWhere('d.producto = :producto')
                ->groupBy('p.fecha')
                ->setParameter("inicio", $fechaInicio)
                ->setParameter("fin", $fechaFin)
                ->setParameter("producto", $idProducto)
        ;
        return $q->getQuery()->getResult();
    }

    public function cantidadPorDiaTotal($fechaInicio, $fechaFin) {

        return $this->getEntityManager()->createQueryBuilder()
                ->select('IDENTITY(d.producto), SUM(d.cantidad) as cantidad')
                ->from('AppBundle:DetalleEnvio', 'd')
                ->join('AppBundle:Envio', 'p', 'WITH', 'd.envio=p.id')
                ->where('p.fecha >= :inicio')
                ->andWhere('p.fecha <= :fin')
                ->groupBy('d.producto')
                ->setParameter("inicio", $fechaInicio)
                ->setParameter("fin", $fechaFin)
                ->getQuery()
                ->getResult();
    }

}
/*select d.producto, p.fecha, SUM(d.cantidad) as cantidad
        from detalle_envio d INNERJOIN envio p ON d.envio=p.id
        WHERE p.fecha>= '2007-1-3' and p.fecha <=: 2017-1-3 groupBy('p.fecha')*/