<?php

namespace AppBundle\Repository;

/**
 * DetalleEnvioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleEnvioRepository extends \Doctrine\ORM\EntityRepository
{
}
