<?php

namespace AppBundle\Repository;

/**
 * EnvioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvioRepository extends \Doctrine\ORM\EntityRepository
{
}
