<?php

namespace AppBundle\Repository;

/**
 * PedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoRepository extends \Doctrine\ORM\EntityRepository
{
   public function getPedidosAbiertos() {

$query = $this->createQueryBuilder('p')
                ->where('p.fechaCierre IS null')
                ->orderBy('p.id', 'ASC')
                ->getQuery()->getResult();
return $query;

}
    
}
