<?php

namespace AppBundle\Repository;

/**
 * PedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoRepository extends \Doctrine\ORM\EntityRepository {

    public function getPedidosAbiertos() {

        return $this->createQueryBuilder('p')
                        ->where('p.fechaCierre IS null')
                        ->orderBy('p.id', 'DESC')
                        ->getQuery()->getResult();
    }

    public function findOrderAll() {
        return $this->createQueryBuilder('p')
                        ->orderBy('p.id', 'DESC')
                        ->getQuery()->getResult();
    }

}
