<?php

namespace AppBundle\Repository;

/**
 * PedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoRepository extends \Doctrine\ORM\EntityRepository
{
  public function getOrdersOpen()
  {
    return $this->createQueryBuilder('p')
          ->where('p.fechaCierre < :fechaCierre')
          ->setParameter('fechaCierre', new \DateTime('now'))
          ->getQuery()->getResult();
  }
}
