<?php

namespace AppBundle\Repository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends \Doctrine\ORM\EntityRepository
{
     public function getStockCritico() {
        
        $query = $this->createQueryBuilder('p')
                ->where('p.stock <= p.stockMinimo')
                ->orderBy('p.nombre', 'ASC')
                ->getQuery();
        $cantidad = count($query->getResult());
        return $cantidad;
    }

}
