<?php

namespace AppBundle\Repository;

/**
 * ProveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllActive()
    {
      return $this->createQueryBuilder('p')
               ->where('p.active = 1')
               ->getQuery()
               ->getResult();
    }

}
