<?php

namespace AppBundle\Repository;

/**
 * SectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectorRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllActive()
    {
      return $this->createQueryBuilder('s')
               ->where('s.active = 1')
               ->getQuery()
               ->getResult();
    }

}
